### ISSUE TITLE
watcher file is not defined

### ISSUE THREAD

**Issue by reintroducing** [adam-lynch/preprocess-cypress-tests-with-vite#1]
Firstly, let me say that I've been rebuilding my whole architecture around Vite after moving from webpack 5 and I'm incredibly close to having everything I want/need working. The last step is to be able to locally run my e2e tests against my localhost so I can update them while developing. It wasn't until I came across your blog post that I could accomplish this, and with your blog I am able to do this without issue (almost), so THANK YOU very much for writing it. 

The reason I say almost is, because when I got to the step to implement the watcher, I ran into an issue. Cypress bombs on this code with the following error: `ReferenceError: file is not defined`

This of course is because `file` is being used but there is no definition for it anywhere in the plugins file: https://github.com/adam-lynch/preprocess-cypress-tests-with-vite/blob/main/cypress/plugins/index.js#L61-L71

How were you able to get this working? Admittedly I haven't downloaded your sample code yet to confirm that it is indeed working but I'm assuming you were testing this all along as you wrote your blog post so I'm really curious how you were able to achieve that.

**Comment by adam-lynch** [comment]
Ah I'm sorry, `file` is the first argument of the `file:preprocessor`callback; see https://github.com/adam-lynch/preprocess-cypress-tests-with-vite/commit/ac44df8193ce009091c3b53b0371b5d916d2ae4f

**Comment by reintroducing** [comment]
ironically my email client was closed so I didn't see you posted this and arrived at the exact same conclusion and came here to tell you that only to see you had already posted it :) 

this works now, thanks again for this write up, i was beginning to question if i really wanted to be on the bleeding edge of this. it doesn't seem like a lot of people are using Vite for these types of things which is a shame because it has really cut down on my config + dependency management needs.

**Comment by adam-lynch** [comment]
Ha, cool.

I completely understand. Well, I initially implemented this for a somewhat complicated suite of tests and it's been working great for a while now. 

> it doesn't seem like a lot of people are using Vite for these types of things

Vite is absolutely taking over (https://patak.dev/vite/ecosystem.html) but yes, no one has written about this yet which I was I felt obligated to! "They" say to write the blog post that you wished existed when you were looking it up.

>it has really cut down on my config + dependency management needs

Yes, this is a big win. In one project we use it for everything except for react-native (not possible yet) and we don't regret it, we just want to use it solely and switch that one last thing over to it 😁

**Comment by najamelan** [comment]
@adam-lynch squatting here to avoid opening another issue, but I have to say Thank you! You just made my day. I wouldn't have come up with this myself, being new to cypress and all.

Btw webpack 4 also doesn't support exports in package.json, so with the nullish operator, I was just trying to deal with the second webpack issue today when your blog post saved me.

ps: as a return on the blog post, it's not uncommon I think to import par of the application/library in the tests, eg. to access types in typescript for example or some helper functions. So I think this technique is well worth it for E2E tests as well.

**Comment by adam-lynch** [comment]
@najamelan that's great! Makes it worthwhile :)

I'll update the blog post to mention exports, in case it helps more people.

>ps: as a return on the blog post, it's not uncommon I think to import par of the application/library in the tests, eg. to access types in typescript for example or some helper functions. So I think this technique is well worth it for E2E tests as well.

True!
